[mypy]
# Kök dizini açıkça belirtiyoruz
mypy_path = .

# Mypy'nin paketleri kafasına göre değil, kesin dizin yapısına göre bulmasını zorluyoruz
explicit_package_bases = True
namespace_packages = True

# Bulunamayan dış kütüphane stub (.pyi) hatalarını yoksayıyoruz
ignore_missing_imports = True
disable_error_code = var-annotated, import-not-found, import-untyped